# Generated by Django 5.2.17 on 2026-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор')], default='client', max_length=10),
        ),
    ]
